In [1]:
import polars as pl
from pathlib import Path

pl.set_random_seed(42)

rmsd = pl.read_parquet(
    "../../data/sourced_antibody_v1/no_antibody/assay_scaffold_simple_metrics.parquet"
).filter(pl.col("mean_pae").is_not_null())

rmsd = rmsd.with_columns(
    pl.when(
        pl.col("mean_pae") < 5,
        pl.col("overall_rmsd") <= 2,
        pl.col("epitope_chunk_rmsd_vs_mpnn") <= 1,
        pl.col("af3_clash_resindices").list.len() == 0,
    )
    .then(pl.lit(True))
    .otherwise(pl.lit(False))
    .alias("success")
)

true_dir = Path("../../data/abdb/complex_pdbfiles/cleaned")
pred_dir = Path("../../data/sourced_antibody_v1/no_antibody/af3_predictions")
mpnn_dir = Path("../../data/sourced_antibody_v1/no_antibody/proteinmpnn")

rmsd_filt = rmsd.filter(
    pl.col("mean_pae") < 5,
    pl.col("overall_rmsd") <= 2,
    pl.col("epitope_chunk_rmsd_vs_mpnn") <= 1,
    pl.col("af3_clash_resindices").list.len() == 0,
    # pl.col("mpnn_clash_resindices").list.len() == 0,
)

In [2]:
pl.Config.set_tbl_rows(10)

id_by_success = (
    rmsd.select(
        "id",
        pl.col("scaffolded_epitope_chunk_resindices").list.len().alias("ep_res"),
        "success",
        "epitope_chunks",
    )
    .group_by("id", "ep_res", "epitope_chunks")
    .agg(
        (pl.col("success").sum() / pl.count("success")).alias("prop_success"),
        pl.count("success").alias("shots_on_goal"),
    )
    .with_columns(
        (pl.col("ep_res") / 104).alias("ep_prop"),
    )
    .filter(pl.col("prop_success") > 0)
    .sort(by="prop_success")
)

rows = []
tot = 0

for id in id_by_success.select("id").to_series().to_list():
    focal_rmsd = rmsd_filt.filter(pl.col("id") == id)

    h = focal_rmsd.height

    if h + tot > 403:
        focal_count = (
            focal_rmsd.group_by("contig_id")
            .agg(
                pl.col("contig_string").count().alias("cnt"),
                pl.col("contig_string").first(),
            )
            .sort(by="cnt", descending=False)
        )

        contig = focal_count.select("contig_string").to_series().to_list()
        cnt = focal_count.select("cnt").to_series().to_list()

        captured_contig = []
        for s, c in zip(contig, cnt):
            if c > 10:
                break

            else:
                rows.append(focal_rmsd.filter(pl.col("contig_string") == s))
                captured_contig.append(s)
                tot += c

        rows.append(
            focal_rmsd.join(
                pl.DataFrame({"contig_string": captured_contig}),
                on="contig_string",
                how="anti",
            ).sample(403 - tot)
        )

    else:
        rows.append(focal_rmsd)

        tot += h

keep = pl.concat(rows)

In [43]:
keep.write_parquet(
    "../../data/sourced_antibody_v1/no_antibody/assay_scaffold_simple_metrics_403.parquet"
)

with open(
    "../../data/sourced_antibody_v1/no_antibody/sourced_antibody_v1_no_antibody_simple_403.fasta",
    "w",
) as f:
    for row in keep.iter_rows(named=True):
        f.write(f">{row['scaffolded_epitope_seq']}\n")
        f.write(row["scaffolded_epitope_seq"] + "\n")

In [29]:
pl.Config.set_tbl_rows(-1)

rmsd_filt.filter(pl.col("id") == "7ox3_0P").group_by("contig_id").agg(
    pl.col("contig_string").count().alias("cnt"), pl.col("contig_string").first()
).sort(by="cnt", descending=True)

shape: (44, 3)
┌───────────┬─────┬────────────────────────────────┐
│ contig_id ┆ cnt ┆ contig_string                  │
│ ---       ┆ --- ┆ ---                            │
│ i64       ┆ u32 ┆ str                            │
╞═══════════╪═════╪════════════════════════════════╡
│ 47        ┆ 43  ┆ 16-16/A6-13/51-51/A63-75/16-16 │
│ 5         ┆ 41  ┆ 17-17/A6-13/49-49/A63-75/17-17 │
│ 49        ┆ 40  ┆ 14-14/A6-13/56-56/A63-75/13-13 │
│ 30        ┆ 35  ┆ 15-15/A6-13/53-53/A63-75/15-15 │
│ 16        ┆ 33  ┆ 20-20/A6-13/44-44/A63-75/19-19 │
│ 10        ┆ 32  ┆ 16-16/A6-13/52-52/A63-75/15-15 │
│ 46        ┆ 32  ┆ 19-19/A6-13/46-46/A63-75/18-18 │
│ 24        ┆ 32  ┆ 15-15/A6-13/54-54/A63-75/14-14 │
│ 18        ┆ 28  ┆ 18-18/A6-13/47-47/A63-75/18-18 │
│ 44        ┆ 28  ┆ 13-13/A6-13/58-58/A63-75/12-12 │
│ 9         ┆ 27  ┆ 14-14/A6-13/55-55/A63-75/14-14 │
│ 28        ┆ 26  ┆ 18-18/A6-13/48-48/A63-75/17-17 │
│ 6         ┆ 26  ┆ 19-19/A6-13/45-45/A63-75/19-19 │
│ 4         ┆ 25  ┆ 12-12/A6-13/60-60/A63-75/11-11 │
│ 1         ┆ 24  ┆ 12-12/A6-13/59-59/A63-75/12-12 │
│ 48        ┆ 24  ┆ 13-13/A6-13/57-57/A63-75/13-13 │
│ 23        ┆ 22  ┆ 17-17/A6-13/50-50/A63-75/16-16 │
│ 17        ┆ 13  ┆ 21-21/A6-13/42-42/A63-75/20-20 │
│ 31        ┆ 11  ┆ 36-36/A6-13/12-12/A63-75/35-35 │
│ 45        ┆ 10  ┆ 34-34/A6-13/16-16/A63-75/33-33 │
│ 50        ┆ 10  ┆ 31-31/A6-13/21-21/A63-75/31-31 │
│ 40        ┆ 8   ┆ 20-20/A6-13/43-43/A63-75/20-20 │
│ 0         ┆ 8   ┆ 32-32/A6-13/19-19/A63-75/32-32 │
│ 3         ┆ 7   ┆ 35-35/A6-13/13-13/A63-75/35-35 │
│ 26        ┆ 5   ┆ 29-29/A6-13/25-25/A63-75/29-29 │
│ 32        ┆ 4   ┆ 30-30/A6-13/23-23/A63-75/30-30 │
│ 35        ┆ 4   ┆ 37-37/A6-13/10-10/A63-75/36-36 │
│ 11        ┆ 4   ┆ 31-31/A6-13/22-22/A63-75/30-30 │
│ 19        ┆ 3   ┆ 21-21/A6-13/41-41/A63-75/21-21 │
│ 20        ┆ 3   ┆ 32-32/A6-13/20-20/A63-75/31-31 │
│ 8         ┆ 3   ┆ 30-30/A6-13/24-24/A63-75/29-29 │
│ 12        ┆ 3   ┆ 29-29/A6-13/26-26/A63-75/28-28 │
│ 52        ┆ 2   ┆ 33-33/A6-13/17-17/A63-75/33-33 │
│ 38        ┆ 2   ┆ 22-22/A6-13/40-40/A63-75/21-21 │
│ 34        ┆ 2   ┆ 34-34/A6-13/15-15/A63-75/34-34 │
│ 27        ┆ 2   ┆ 36-36/A6-13/11-11/A63-75/36-36 │
│ 21        ┆ 1   ┆ 24-24/A6-13/36-36/A63-75/23-23 │
│ 39        ┆ 1   ┆ 28-28/A6-13/27-27/A63-75/28-28 │
│ 51        ┆ 1   ┆ 37-37/A6-13/9-9/A63-75/37-37   │
│ 42        ┆ 1   ┆ 23-23/A6-13/38-38/A63-75/22-22 │
│ 29        ┆ 1   ┆ 23-23/A6-13/37-37/A63-75/23-23 │
│ 37        ┆ 1   ┆ 38-38/A6-13/8-8/A63-75/37-37   │
│ 25        ┆ 1   ┆ 24-24/A6-13/35-35/A63-75/24-24 │
│ 22        ┆ 1   ┆ 22-22/A6-13/39-39/A63-75/22-22 │
└───────────┴─────┴────────────────────────────────┘

In [ ]:
# pl.Config.set_tbl_rows(-1)

# rmsd.select(
#     "id",
#     pl.col("scaffolded_epitope_chunk_resindices").list.len().alias("ep_res"),
#     "success",
#     "epitope_chunks",
# ).group_by("id", "ep_res", "epitope_chunks").agg(
#     (pl.col("success").sum() / pl.count("success")).alias("prop_success"),
#     pl.count("success").alias("shots_on_goal"),
# ).with_columns(
#     (pl.col("ep_res") / 104).alias("ep_prop"),
# ).sort(
#     by="ep_prop", descending=True
# )

shape: (59, 6)
┌─────────┬────────┬────────────────┬──────────────┬───────────────┬──────────┐
│ id      ┆ ep_res ┆ epitope_chunks ┆ prop_success ┆ shots_on_goal ┆ ep_prop  │
│ ---     ┆ ---    ┆ ---            ┆ ---          ┆ ---           ┆ ---      │
│ str     ┆ u32    ┆ i64            ┆ f64          ┆ u32           ┆ f64      │
╞═════════╪════════╪════════════════╪══════════════╪═══════════════╪══════════╡
│ 2xqb_0P ┆ 56     ┆ 2              ┆ 0.0          ┆ 2624          ┆ 0.538462 │
│ 8t58_0P ┆ 56     ┆ 2              ┆ 0.0          ┆ 322           ┆ 0.538462 │
│ 3ma9_0P ┆ 54     ┆ 2              ┆ 0.0          ┆ 2368          ┆ 0.519231 │
│ 8j7e_0P ┆ 46     ┆ 1              ┆ 0.0          ┆ 7             ┆ 0.442308 │
│ 7zxk_1P ┆ 40     ┆ 2              ┆ 0.0          ┆ 398           ┆ 0.384615 │
│ 5eu7_1P ┆ 38     ┆ 2              ┆ 0.0          ┆ 3648          ┆ 0.365385 │
│ 8oxv_0P ┆ 36     ┆ 2              ┆ 0.0          ┆ 418           ┆ 0.346154 │
│ 6ye3_2P ┆ 36     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.346154 │
│ 5kw9_0P ┆ 36     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.346154 │
│ 8trt_1P ┆ 35     ┆ 2              ┆ 0.0          ┆ 314           ┆ 0.336538 │
│ 7o52_0P ┆ 34     ┆ 1              ┆ 0.0          ┆ 64            ┆ 0.326923 │
│ 6oan_0P ┆ 33     ┆ 2              ┆ 0.0          ┆ 2560          ┆ 0.317308 │
│ 4zfg_0P ┆ 33     ┆ 2              ┆ 0.0          ┆ 2560          ┆ 0.317308 │
│ 7kql_0P ┆ 32     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.307692 │
│ 4u6v_0P ┆ 32     ┆ 2              ┆ 0.0          ┆ 2560          ┆ 0.307692 │
│ 8uky_1P ┆ 32     ┆ 2              ┆ 0.0          ┆ 433           ┆ 0.307692 │
│ 6wmw_1P ┆ 31     ┆ 2              ┆ 0.0          ┆ 3968          ┆ 0.298077 │
│ 4xwo_5P ┆ 31     ┆ 2              ┆ 0.006104     ┆ 4096          ┆ 0.298077 │
│ 6o39_0P ┆ 30     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.288462 │
│ 8wsq_0P ┆ 30     ┆ 2              ┆ 0.0          ┆ 395           ┆ 0.288462 │
│ 6fgb_0P ┆ 29     ┆ 1              ┆ 0.0          ┆ 64            ┆ 0.278846 │
│ 8yx9_0P ┆ 29     ┆ 1              ┆ 0.0          ┆ 10            ┆ 0.278846 │
│ 7uxl_1P ┆ 29     ┆ 2              ┆ 0.0          ┆ 549           ┆ 0.278846 │
│ 8jel_0P ┆ 27     ┆ 1              ┆ 0.0          ┆ 8             ┆ 0.259615 │
│ 7tzh_0P ┆ 27     ┆ 2              ┆ 0.0          ┆ 1958          ┆ 0.259615 │
│ 8pww_0P ┆ 27     ┆ 2              ┆ 0.037288     ┆ 295           ┆ 0.259615 │
│ 8jnk_3P ┆ 26     ┆ 2              ┆ 0.020134     ┆ 298           ┆ 0.25     │
│ 5o4g_0P ┆ 26     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.25     │
│ 6phb_1P ┆ 25     ┆ 1              ┆ 0.0          ┆ 64            ┆ 0.240385 │
│ 3ux9_1P ┆ 24     ┆ 2              ┆ 0.0          ┆ 4416          ┆ 0.230769 │
│ 5lsp_0P ┆ 24     ┆ 1              ┆ 0.0          ┆ 64            ┆ 0.230769 │
│ 5gjs_0P ┆ 23     ┆ 2              ┆ 0.0          ┆ 4224          ┆ 0.221154 │
│ 6ztr_0P ┆ 23     ┆ 2              ┆ 0.0          ┆ 4224          ┆ 0.221154 │
│ 7dm1_0P ┆ 23     ┆ 1              ┆ 0.0          ┆ 64            ┆ 0.221154 │
│ 3lhp_1P ┆ 23     ┆ 1              ┆ 0.0          ┆ 64            ┆ 0.221154 │
│ 6xxv_0P ┆ 22     ┆ 1              ┆ 0.03125      ┆ 64            ┆ 0.211538 │
│ 8db4_0P ┆ 22     ┆ 2              ┆ 0.003175     ┆ 315           ┆ 0.211538 │
│ 8ee0_0P ┆ 21     ┆ 1              ┆ 0.0          ┆ 7             ┆ 0.201923 │
│ 7ox3_0P ┆ 21     ┆ 2              ┆ 0.185731     ┆ 3392          ┆ 0.201923 │
│ 7yv1_0P ┆ 20     ┆ 1              ┆ 0.0          ┆ 5             ┆ 0.192308 │
│ 6okm_0P ┆ 20     ┆ 2              ┆ 0.0          ┆ 1728          ┆ 0.192308 │
│ 5l6y_0P ┆ 20     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.192308 │
│ 6ppg_1P ┆ 20     ┆ 2              ┆ 0.0          ┆ 1728          ┆ 0.192308 │
│ 6qb6_0P ┆ 19     ┆ 2              ┆ 0.0          ┆ 4736          ┆ 0.182692 │
│ 6o9i_0P ┆ 19     ┆ 2              ┆ 0.002604     ┆ 4608          ┆ 0.182692 │
│ 7so5_0P ┆ 19     ┆ 2              ┆ 0.0          ┆ 4224          ┆ 0.182692 │
│ 5j13_0P ┆ 18     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.173077 │
│ 3q1s_0P ┆ 18     ┆ 2              ┆ 0.0          ┆ 2560          ┆ 0.173077 │
│ 4nnp_0P ┆ 18     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.173077 │
│ 2h32_0P ┆ 17     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.163462 │
│ 4kv5_3P ┆ 17     ┆ 2              ┆ 0.0          ┆ 1728          ┆ 0.163462 │
│ 6wgl_0P ┆ 17     ┆ 2              ┆ 0.0          ┆ 3392          ┆ 0.163462 │
│ 2qqn_0P ┆ 16     ┆ 2              ┆ 0.0          ┆ 2560          ┆ 0.153846 │
│ 6cyf_0P ┆ 16     ┆ 2              ┆ 0.0          ┆ 1728          ┆ 0.153846 │
│ 8cz8_1P ┆ 16     ┆ 2              ┆ 0.005263     ┆ 570           ┆ 0.153846 │
│ 6ol6_1P ┆ 15     ┆ 2              ┆ 0.0          ┆ 4224          ┆ 0.144231 │
│ 5fhx_1P ┆ 15     ┆ 2              ┆ 0.035275     ┆ 4224          ┆ 0.144231 │
│ 8ol9_0P ┆ 12     ┆ 1              ┆ 0.0          ┆ 5             ┆ 0.115385 │
│ 7a3t_0P ┆ 4      ┆ 2              ┆ 0.000391     ┆ 2560          ┆ 0.038462 │
└─────────┴────────┴────────────────┴──────────────┴───────────────┴──────────┘

In [12]:
rmsd_filt.select(
    "id",
    pl.col("scaffolded_epitope_chunk_resindices").list.len().alias("ep_res"),
    pl.col("scaffolded_epitope_seq").str.len_chars().alias("total_res"),
).unique().with_columns((pl.col("ep_res") / pl.col("total_res")).alias("ep_prop")).sort(
    by="ep_prop", descending=True
)

shape: (10, 4)
┌─────────┬────────┬───────────┬──────────┐
│ id      ┆ ep_res ┆ total_res ┆ ep_prop  │
│ ---     ┆ ---    ┆ ---       ┆ ---      │
│ str     ┆ u32    ┆ u32       ┆ f64      │
╞═════════╪════════╪═══════════╪══════════╡
│ 4xwo_5P ┆ 31     ┆ 104       ┆ 0.298077 │
│ 8pww_0P ┆ 27     ┆ 104       ┆ 0.259615 │
│ 8jnk_3P ┆ 26     ┆ 104       ┆ 0.25     │
│ 8db4_0P ┆ 22     ┆ 104       ┆ 0.211538 │
│ 6xxv_0P ┆ 22     ┆ 104       ┆ 0.211538 │
│ 7ox3_0P ┆ 21     ┆ 104       ┆ 0.201923 │
│ 6o9i_0P ┆ 19     ┆ 104       ┆ 0.182692 │
│ 8cz8_1P ┆ 16     ┆ 104       ┆ 0.153846 │
│ 5fhx_1P ┆ 15     ┆ 104       ┆ 0.144231 │
│ 7a3t_0P ┆ 4      ┆ 104       ┆ 0.038462 │
└─────────┴────────┴───────────┴──────────┘

In [14]:
from mdaf3.AF3OutputParser import AF3Output
import MDAnalysis as mda
from MDAnalysis.analysis import rms
from MDAnalysis.analysis.align import alignto
import numpy as np


def num_clashing_interactions_mpnn(row, af3_dir, mpnn_dir, true_dir):
    af3_output = AF3Output(af3_dir / row["assay_scaffolded_epitope_id"])
    af3_u = af3_output.get_mda_universe()
    af3_ris = row["assay_scaffolded_epitope_chunk_resindices"]

    mpnn_u = mda.Universe(
        ((mpnn_dir / row["id"]) / str(row["contig_id"]))
        / (
            row["id"]
            + "_"
            + str(row["rfd_id"])
            + "_fixed_dldesign_"
            + str(row["mpnn_id"])
            + ".pdb"
        )
    )
    mpnn_ris = row["scaffolded_epitope_chunk_resindices"]

    true_u = mda.Universe(true_dir / (row["id"] + ".pdb"))
    true_u.atoms.write("true.pdb")

    true_ris = row["epitope_chunk_resindices"]

    alignto(
        mpnn_u.residues[mpnn_ris].atoms.select_atoms("backbone"),
        true_u.residues[true_ris].atoms.select_atoms("backbone"),
    )

    # print(mpnn_u.residues[mpnn_ris].atoms.select_atoms("name CA").positions[:10])
    # print(true_u.residues[true_ris].atoms.select_atoms("name CA").positions[:10])

    mpnn_combined_u = mda.Merge(
        mpnn_u.atoms, true_u.atoms.select_atoms("segid B or segid C")
    )
    mpnn_combined_u.atoms.write("mpnn_combined.pdb")

    tmp_boolmask = np.full(len(mpnn_u.residues), False)
    tmp_boolmask[mpnn_ris] = True
    unintended_res = mpnn_combined_u.select_atoms("segid A").residues[~tmp_boolmask]

    row["mpnn_clash_resindices"] = list(
        mpnn_combined_u.select_atoms(
            "((segid B or segid C) and (not name H*)) and around 4 group unintended",
            unintended=unintended_res.atoms,
        ).residues.resindices
    )

    alignto(
        af3_u.residues[af3_ris].atoms.select_atoms("backbone"),
        true_u.residues[true_ris].atoms.select_atoms("backbone"),
    )
    # af3_u.atoms.chainIDs = ["D"] * len(af3_u.atoms)
    # af3_combined_u = mda.Merge(
    #     af3_u.atoms, true_u.atoms
    # )

    af3_combined_u = mda.Merge(
        af3_u.atoms, true_u.atoms.select_atoms("segid B or segid C")
    )
    af3_combined_u.atoms.write("af3_combined.pdb")
    tmp_boolmask = np.full(len(af3_u.residues), False)
    tmp_boolmask[af3_ris] = True
    unintended_res = af3_combined_u.select_atoms("segid A").residues[~tmp_boolmask]
    # print(unintended_res)
    # print(unintended_res.atoms.select_atoms("segid A and (not name H*)"))

    l = list(
        af3_combined_u.atoms.select_atoms(
            "((segid B or segid C) and (not name H*)) and around 4 group unintended",
            unintended=unintended_res.atoms,
        ).residues.resindices
    )

    # if len(l) > 0:
    #     print("Clash dectected")

    row["af3_clash_resindices"] = l

    return row

In [6]:
from mdaf3.FeatureExtraction import serial_apply, split_apply_combine
import warnings

warnings.filterwarnings("ignore")


rmsd = split_apply_combine(
    rmsd, num_clashing_interactions_mpnn, pred_dir, mpnn_dir, true_dir, chunksize=15
)

100%|██████████| 62254/62254 [07:13<00:00, 143.72it/s]

In [22]:
no_clash = rmsd.filter(pl.col("af3_clash_resindices").list.len() == 0)

In [23]:
no_clash.filter(
    pl.col("mean_pae") < 5,
    pl.col("overall_rmsd") <= 2,
    pl.col("epitope_chunk_rmsd_vs_mpnn") <= 1,
)

shape: (268, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ antigen_s ┆ heavy_seq ┆ light_seq ┆ epitope_s ┆ … ┆ epitope_c ┆ mean_pae ┆ mpnn_clas ┆ af3_clash │
│ eq        ┆ ---       ┆ ---       ┆ eq        ┆   ┆ hunk_rmsd ┆ ---      ┆ h_resindi ┆ _resindic │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ _vs_mpnn  ┆ f64      ┆ ces       ┆ es        │
│ str       ┆           ┆           ┆ str       ┆   ┆ ---       ┆          ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆          ┆ list[i64] ┆ list[i64] │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ DLTVEPNLH ┆ VQLVESGGG ┆ DIQMTQSPS ┆ FLYERIQIV ┆ … ┆ 0.593783  ┆ 4.943669 ┆ []        ┆ []        │
│ SLITSTTHK ┆ LVQPGGSLR ┆ SLSASVGDR ┆ NQELYEDF  ┆   ┆           ┆          ┆           ┆           │
│ WIFVGGKGG ┆ LSCAASGFN ┆ VTITCRASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ VGK…      ┆ LYY…      ┆ SVS…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ DLTVEPNLH ┆ VQLVESGGG ┆ DIQMTQSPS ┆ FLYERIQIV ┆ … ┆ 0.594184  ┆ 4.568315 ┆ []        ┆ []        │
│ SLITSTTHK ┆ LVQPGGSLR ┆ SLSASVGDR ┆ NQELYEDF  ┆   ┆           ┆          ┆           ┆           │
│ WIFVGGKGG ┆ LSCAASGFN ┆ VTITCRASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ VGK…      ┆ LYY…      ┆ SVS…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ DLTVEPNLH ┆ VQLVESGGG ┆ DIQMTQSPS ┆ FLYERIQIV ┆ … ┆ 0.620923  ┆ 4.877741 ┆ []        ┆ []        │
│ SLITSTTHK ┆ LVQPGGSLR ┆ SLSASVGDR ┆ NQELYEDF  ┆   ┆           ┆          ┆           ┆           │
│ WIFVGGKGG ┆ LSCAASGFN ┆ VTITCRASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ VGK…      ┆ LYY…      ┆ SVS…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ DLTVEPNLH ┆ VQLVESGGG ┆ DIQMTQSPS ┆ FLYERIQIV ┆ … ┆ 0.602041  ┆ 4.765648 ┆ []        ┆ []        │
│ SLITSTTHK ┆ LVQPGGSLR ┆ SLSASVGDR ┆ NQELYEDF  ┆   ┆           ┆          ┆           ┆           │
│ WIFVGGKGG ┆ LSCAASGFN ┆ VTITCRASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ VGK…      ┆ LYY…      ┆ SVS…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ DLTVEPNLH ┆ VQLVESGGG ┆ DIQMTQSPS ┆ FLYERIQIV ┆ … ┆ 0.538666  ┆ 4.313558 ┆ []        ┆ []        │
│ SLITSTTHK ┆ LVQPGGSLR ┆ SLSASVGDR ┆ NQELYEDF  ┆   ┆           ┆          ┆           ┆           │
│ WIFVGGKGG ┆ LSCAASGFN ┆ VTITCRASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ VGK…      ┆ LYY…      ┆ SVS…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ NIANSIDIL ┆ QVQLQESGP ┆ DIQMTQSPS ┆ AFKIAKMDK ┆ … ┆ 0.330935  ┆ 4.979327 ┆ []        ┆ []        │
│ QEKEGHLDF ┆ GLVKPSETL ┆ SLSASVGDR ┆ NYTNE     ┆   ┆           ┆          ┆           ┆           │
│ VIIPHYTFL ┆ SLTCTVSGG ┆ VTITCQASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ DYY…      ┆ PIS…      ┆ DIN…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ NIANSIDIL ┆ QVQLQESGP ┆ DIQMTQSPS ┆ AFKIAKMDK ┆ … ┆ 0.382999  ┆ 4.615634 ┆ []        ┆ []        │
│ QEKEGHLDF ┆ GLVKPSETL ┆ SLSASVGDR ┆ NYTNE     ┆   ┆           ┆          ┆           ┆           │
│ VIIPHYTFL ┆ SLTCTVSGG ┆ VTITCQASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ DYY…      ┆ PIS…      ┆ DIN…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ NIANSIDIL ┆ QVQLQESGP ┆ DIQMTQSPS ┆ AFKIAKMDK ┆ … ┆ 0.776294  ┆ 4.915735 ┆ []        ┆ []        │
│ QEKEGHLDF ┆ GLVKPSETL ┆ SLSASVGDR ┆ NYTNE     ┆   ┆           ┆          ┆           ┆           │
│ VIIPHYTFL ┆ SLTCTVSGG ┆ VTITCQASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ DYY…      ┆ PIS…      ┆ DIN…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ NIANSIDIL ┆ QVQLQESGP ┆ DIQMTQSPS ┆ AFKIAKMDK ┆ … ┆ 0.373468  ┆ 4.025345 ┆ []        ┆ []        │
│ QEKEGHLDF ┆ GLVKPSETL ┆ SLSASVGDR ┆ NYTNE     ┆   ┆           ┆          ┆           ┆           │
│ VIIPHYTFL ┆ SLTCTVSGG ┆ VTITCQASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ DYY…      ┆ PIS…      ┆ DIN…      ┆           ┆   ┆           ┆          ┆           ┆           │
│ NIANSIDIL ┆ QVQLQESGP ┆ DIQMTQSPS ┆ AFKIAKMDK ┆ … ┆ 0.425911  ┆ 4.785652 ┆ []        ┆ []        │
│ QEKEGHLDF ┆ GLVKPSETL ┆ SLSASVGDR ┆ NYTNE     ┆   ┆           ┆          ┆           ┆           │
│ VIIPHYTFL ┆ SLTCTVSGG ┆ VTITCQASQ ┆           ┆   ┆           ┆          ┆           ┆           │
│ DYY…      ┆ PIS…      ┆ DIN…      ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [18]:
no_clash.filter(
    pl.col("mean_pae") < 5,
    pl.col("overall_rmsd") <= 2,
    pl.col("epitope_chunk_rmsd_vs_mpnn") <= 1,
).select("id").unique()

shape: (7, 1)
┌─────────┐
│ id      │
│ ---     │
│ str     │
╞═════════╡
│ 8pww_0P │
│ 8jnk_3P │
│ 7ox3_0P │
│ 8db4_0P │
│ 4xwo_5P │
│ 8cz8_1P │
│ 5fhx_1P │
└─────────┘

In [ ]:
rmsd.filter(
    pl.col("af3_clash_resindices").list.len() == 0,
    pl.col("mpnn_clash_resindices").list.len() != 0,
).filter(
    pl.col("mean_pae") < 5,
    pl.col("overall_rmsd") <= 2,
    pl.col("epitope_chunk_rmsd_vs_mpnn") <= 1,
).select(
    pl.col("mpnn_clash_resindices").list.len().max()
)

shape: (1, 1)
┌───────────────────────┐
│ mpnn_clash_resindices │
│ ---                   │
│ u32                   │
╞═══════════════════════╡
│ 2                     │
└───────────────────────┘

In [15]:
rmsd = split_apply_combine(
    rmsd.filter(
        pl.col("af3_clash_resindices").list.len() == 0,
        pl.col("mpnn_clash_resindices").list.len() != 0,
    ).filter(
        pl.col("mean_pae") < 5,
        pl.col("overall_rmsd") <= 2,
        pl.col("epitope_chunk_rmsd_vs_mpnn") <= 1,
    )[
        0
    ],
    num_clashing_interactions_mpnn,
    pred_dir,
    mpnn_dir,
    true_dir,
    chunksize=15,
)

100%|██████████| 1/1 [00:00<00:00,  3.54it/s]